# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/argoproj.io/application_v1alpha1.json
{{ $name := include "telemetry-system.fullname" . -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Namespace }}-{{ $name }}-clickhouse
  namespace: {{ .Values.argocdNamespace }}
  labels:
    {{- include "telemetry-system.labels" . | nindent 4 }}
spec:
  project: {{ .Release.Namespace }}-{{ $name }}
  source:
    chart: altinity-clickhouse-operator
    repoURL: https://docs.altinity.com/clickhouse-operator
    targetRevision: {{ .Values.versions.clickhouseOperator }}
    helm:
      releaseName: clickhouse-operator
      valuesObject:
        operator:
          image:
            repository: docker.io/altinity/clickhouse-operator
        metrics:
          image:
            repository: docker.io/altinity/metrics-exporter
        configs:
          files:
            config.yaml:
              watch:
                namespaces: [".*"]
  destination:
    name: {{ .Release.Namespace }}/{{ .Values.destinationCluster }}
    namespace: clickhouse-operator
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: -1
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 60s
