apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFluentBitConfig
metadata:
  name: {{ include "telemetry-exporter-components.fullname" . }}
  labels:
    {{- include "telemetry-exporter-components.labels" . | nindent 4 }}
spec:
  inputSelector:
    matchLabels:
      fluentbit.fluent.io/enabled: 'true'
      fluentbit.fluent.io/mode: k8s
  filterSelector:
    matchLabels:
      fluentbit.fluent.io/enabled: 'true'
      fluentbit.fluent.io/mode: k8s
  outputSelector:
    matchLabels:
      fluentbit.fluent.io/enabled: 'true'
      fluentbit.fluent.io/mode: k8s
