{{ $name := include "telemetry-exporter-components.fullname" . -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $name }}-targetallocator
  labels:
    {{- include "telemetry-exporter-components.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ $name }}-targetallocator
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ $name }}-targetallocator
  apiGroup: rbac.authorization.k8s.io
