apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFilter
metadata:
  name: {{ include "telemetry-exporter-components.fullname" . }}
  labels:
    fluentbit.fluent.io/enabled: 'true'
    fluentbit.fluent.io/mode: k8s
    {{- include "telemetry-exporter-components.labels" . | nindent 4 }}
spec:
  match: kube.*
  filters:
    - kubernetes:
        labels: true
        annotations: false
    - nest:
        operation: lift
        nestedUnder: kubernetes
        addPrefix: kubernetes_
    - nest:
        operation: lift
        nestedUnder: kubernetes_labels
        addPrefix: labels_kubernetes_
    - modify:
        rules:
          # Indexed labels.
          - copy:
              kubernetes_namespace_name: k8s.namespace.name
          - rename:
              kubernetes_container_name: k8s.container.name
              kubernetes_pod_name: k8s.pod.name
              kubernetes_host: k8s.node.host
              kubernetes_namespace_name: service.namespace
              labels_kubernetes_app.kubernetes.io/component: service.component
              labels_kubernetes_app.kubernetes.io/instance: service.instance.id
              labels_kubernetes_app.kubernetes.io/name: service.name
          - set:
              k8s.cluster.name: {{ .Values.clusterName }}
          # Metadata.
          # - copy:
          #     kubernetes_container_image: k8s.container.image
          - removeRegex: kubernetes.*
