apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "telemetry-exporter-components.fullname" . }}-collector
  namespace: {{ .Values.openTelemetry.namespace }}
  labels:
    {{- include "telemetry-exporter-components.labels" . | nindent 4 }}
