{{ $name := include "telemetry-exporter-components.fullname" . -}}
apiVersion: fluentbit.fluent.io/v1alpha2
kind: FluentBit
metadata:
  name: {{ $name }}
  labels:
    {{- include "telemetry-exporter-components.labels" . | nindent 4 }}
spec:
  image: kubesphere/fluent-bit:3.0.7
  positionDB:
    hostPath:
      path: /var/lib/fluent-bit/
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  fluentBitConfigName: {{ $name }}
  tolerations:
    - operator: Exists
