{{ $name := include "telemetry-exporter-components.fullname" . -}}
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: {{ $name }}
  labels:
    {{- include "telemetry-exporter-components.labels" . | nindent 4 }}
spec:
  mode: statefulset
  targetAllocator:
    enabled: true
    serviceAccount: {{ $name }}-targetallocator
    prometheusCR:
      enabled: true
      serviceMonitorSelector: {}
      podMonitorSelector: {}
  config:
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}
      prometheus:
        config:
          scrape_configs: []

    processors:
      batch: {}

    exporters:
      otlp:
        endpoint: {{ .Values.exporterOTLPEndpoint }}
        tls:
          insecure: true

    service:
      pipelines:
        metrics:
          receivers: [otlp, prometheus]
          processors: [batch]
          exporters: [otlp]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
