{{ $name := include "telemetry-exporter-components.fullname" . -}}
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: {{ $name }}
  labels:
    {{- include "telemetry-exporter-components.labels" . | nindent 4 }}
spec:
  mode: statefulset
  targetAllocator:
    enabled: true
    serviceAccount: {{ $name }}-targetallocator
    prometheusCR:
      enabled: true
      serviceMonitorSelector: {}
      podMonitorSelector: {}
  config:
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}
      prometheus:
        config:
          scrape_configs: []
        target_allocator:
          endpoint: http://{{ $name }}-targetallocator:80
          interval: 30s
          collector_id: $POD_NAME


    exporters:
      debug:
        verbosity: detailed

    service:
      pipelines:
        metrics:
          receivers: [otlp, prometheus]
          processors: []
          exporters: [debug]
        logs:
          receivers: [otlp]
          processors: []
          exporters: [debug]
