apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "telemetry-exporter-components.fullname" . }}-targetallocator
  labels:
    {{- include "telemetry-exporter-components.labels" . | nindent 4 }}
