# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/clickhouse.altinity.com/clickhouseinstallation_v1.json
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: logs
  namespace: telemetry-system
  labels:
    {{- include "telemetry-system-components.labels" . | nindent 4 }}
spec:
  defaults:
    templates:
      serviceTemplate: svc-template-1
  templates:
    serviceTemplates:
      - name: svc-template-1
        generateName: clickhouse-{chi}
        spec:
          ports:
            - name: https
              port: 443
              targetPort: https
            - name: secureclient
              port: 9443
              targetPort: secureclient
    podTemplates:
      - name: clickhouse-pod-template
        spec:
          containers:
            - name: clickhouse
              image: docker.io/altinity/clickhouse-server:25.3.6.10034.altinitystable
              volumeMounts:
                - name: clickhouse-storage
                  mountPath: /var/lib/clickhouse
    volumeClaimTemplates:
      - name: clickhouse-storage
        spec: {{- .Values.clickhouse.pvcTemplateSpec | toYaml | nindent 10 }}
  configuration:
    users:
      grafana/ssl_certificates/common_name: clickhouse-logs.telemetry-system.svc.cluster.local/grafana
      grafana/networks/ip: ::/0
      grafana/profile: default
      grafana/access_management: 1
      collector/ssl_certificates/common_name: clickhouse-logs.telemetry-system.svc.cluster.local/collector
      collector/networks/ip: ::/0
      collector/profile: default
      collector/access_management: 1
    clusters:
      - name: cluster01
        secure: "True"
        layout:
          shardsCount: 1
          replicasCount: 1
        templates:
          podTemplate: clickhouse-pod-template
    settings:
      tcp_port_secure: 9443
      https_port: 8443
    files:
      openssl.xml: |
        <yandex>
          <openSSL>
            <server>
              <certificateFile>/etc/clickhouse-server/secrets.d/tls.crt/logs-server-tls/tls.crt</certificateFile>
              <privateKeyFile>/etc/clickhouse-server/secrets.d/tls.key/logs-server-tls/tls.key</privateKeyFile>
              <caConfig>/etc/clickhouse-server/secrets.d/ca.crt/logs-server-tls/ca.crt</caConfig>
              <verificationMode>strict</verificationMode>
              <loadDefaultCAFile>false</loadDefaultCAFile>
              <cacheSessions>true</cacheSessions>
              <disableProtocols>sslv2,sslv3</disableProtocols>
              <preferServerCiphers>true</preferServerCiphers>
            </server>
          </openSSL>
        </yandex>
      tls.crt:
        valueFrom:
          secretKeyRef:
            name: logs-server-tls
            key: tls.crt
      tls.key:
        valueFrom:
          secretKeyRef:
            name: logs-server-tls
            key: tls.key
      ca.crt:
        valueFrom:
          secretKeyRef:
            name: logs-server-tls
            key: ca.crt
