# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/grafana.integreatly.org/grafanadatasource_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: {{ include "telemetry-system-components.fullname" . }}-grafana-clickhouse
  labels:
    {{- include "telemetry-system-components.labels" . | nindent 4 }}
spec:
  valuesFrom:
    - targetPath: secureJsonData.tlsCACert
      valueFrom:
        secretKeyRef:
          key: ca.crt
          name: logs-grafana-tls
    - targetPath: secureJsonData.tlsClientCert
      valueFrom:
        secretKeyRef:
          key: tls.crt
          name: logs-grafana-tls
    - targetPath: secureJsonData.tlsClientKey
      valueFrom:
        secretKeyRef:
          key: tls.key
          name: logs-grafana-tls
  datasource:
    name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    jsonData:
      host: clickhouse-logs.telemetry-system.svc.cluster.local
      port: 9443
      secure: true
      username: grafana
      tlsAuth: true
      tlsAuthWithCACert: true
    secureJsonData:
      tlsCACert: ${ca.crt}
      tlsClientCert: ${tls.crt}
      tlsClientKey: ${tls.key}
  instanceSelector:
    matchLabels:
      app.kubernetes.io/component: grafana
      {{- include "telemetry-system-components.selector-labels" . | nindent 6 }}
  plugins:
    - name: grafana-clickhouse-datasource
      version: 4.11.1
