{{ $name := include "telemetry-system-components.fullname" . -}}
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: {{ $name }}
  labels:
    {{- include "telemetry-system-components.labels" . | nindent 4 }}
spec:
  mode: deployment
  config:
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}

    processors:
      batch: {}
      attributes:
        actions:
          - action: insert
            key: loki.attribute.labels
            value: k8s.pod.name, k8s.container.name, k8s.namespace.name, k8s.node.host, k8s.cluster.name, service.name, service.instance.id, service.namespace, service.component

    exporters:
      # Yeah the Loki exporter is deprecated, but the OTLP endpoint in Loki refuses to index labels correctly.
      # Should switch to otlphttp exporter for Loki when they get it actually working and I'm not one of the first users.
      loki:
        endpoint: {{ .Values.lokiEndpoint }}
      prometheus:
        endpoint: 0.0.0.0:9000
      debug:
        verbosity: detailed

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheus]
        logs:
          receivers: [otlp]
          processors: [batch, attributes]
          exporters: [loki]
