# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/opentelemetry.io/opentelemetrycollector_v1beta1.json
{{ $name := include "telemetry-system-components.fullname" . -}}
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: {{ $name }}
  labels:
    {{- include "telemetry-system-components.labels" . | nindent 4 }}
spec:
  mode: deployment
  volumeMounts:
    - mountPath: /etc/certificate
      name: certificate
      readOnly: true
  volumes:
    - name: certificate
      secret:
        secretName: logs-collector-tls
  config:
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}

    processors:
      batch: {}

    exporters:
      clickhouse:
        endpoint: https://clickhouse-logs.telemetry-system.svc.cluster.local
        database: otel
        ttl: 720h
        username: collector
        tls:
          ca_file: /etc/certificate/ca.crt
          cert_file: /etc/certificate/tls.crt
          key_file: /etc/certificate/tls.key
        logs_table_name: otel_logs
      prometheusremotewrite:
        endpoint: {{ .Values.prometheusRemoteWriteEndpoint }}
        resource_to_telemetry_conversion:
          enabled: true

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheusremotewrite]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [clickhouse]
