# Default values for telemetry-system-components.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: "" # Override chart name.
fullnameOverride: "" # Override full release name.

otel:
  service:
    annotations: # Annotations to add to the OpenTelemetry Collector LoadBalancer service.
      external-dns.alpha.kubernetes.io/hostname: otel.infra.sneakybugs.com

prometheusRemoteWriteEndpoint: http://prometheus-prometheus.telemetry-system:9090/api/v1/write

grafana:
  # TODO Insert this everywhere and split Grafana to separate namespace.
  namespace: telemetry-system
  httproute:
    parentRefs:
      - name: external
        namespace: envoy
    hostname: grafana.infra.sneakybugs.com

clickhouse:
  namespace: clickhouse-operator
  pvcTemplateSpec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
