# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/argoproj.io/application_v1alpha1.json
{{ $name := include "cluster.fullname" . -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Namespace }}-{{ $name }}-system-calico
  namespace: {{ .Values.argocdNamespace }}
  labels:
    {{- include "cluster.labels" . | nindent 4 }}
spec:
  ignoreDifferences:
    - group: projectcalico.org
      kind: FelixConfiguration
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
  project: {{ .Release.Namespace }}-{{ $name }}-system
  source:
    chart: tigera-operator
    repoURL: https://docs.tigera.io/calico/charts
    targetRevision: {{ .Values.versions.calico }}
    helm:
      releaseName: tigera-operator
      valuesObject:
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 256Mi
        goldmane:
          goldmaneDeployment:
            spec:
              template:
                spec:
                  containers:
                    - name: goldmane
                      resources:
                        requests:
                          cpu: 50m
                          memory: 64Mi
                        limits:
                          cpu: 100m
                          memory: 128Mi
        whisker:
          whiskerDeployment:
            spec:
              template:
                spec:
                  containers:
                    - name: whisker
                      resources:
                        requests:
                          cpu: 10m
                          memory: 16Mi
                        limits:
                          cpu: 10m
                          memory: 32Mi
                    - name: whisker-backend
                      resources:
                        requests:
                          cpu: 10m
                          memory: 16Mi
                        limits:
                          cpu: 10m
                          memory: 32Mi
        apiServer:
          apiServerDeployment:
            spec:
              template:
                spec:
                  containers:
                    - name: calico-apiserver
                      resources:
                        requests:
                          cpu: 50m
                          memory: 128Mi
                        limits:
                          cpu: 100m
                          memory: 256Mi
        installation:
          calicoNodeDaemonSet:
            spec:
              template:
                spec:
                  containers:
                    - name: calico-node
                      resources:
                        requests:
                          cpu: 50m
                          memory: 128Mi
                        limits:
                          cpu: 100m
                          memory: 256Mi
          csiNodeDriverDaemonSet:
            spec:
              template:
                spec:
                  containers:
                    - name: calico-csi
                      resources:
                        requests:
                          cpu: 50m
                          memory: 32Mi
                        limits:
                          cpu: 100m
                          memory: 64Mi
                    - name: csi-node-driver-registrar
                      resources:
                        requests:
                          cpu: 50m
                          memory: 32Mi
                        limits:
                          cpu: 100m
                          memory: 64Mi
          calicoKubeControllersDeployment:
            spec:
              template:
                spec:
                  containers:
                    - name: calico-kube-controllers
                      resources:
                        requests:
                          cpu: 50m
                          memory: 32Mi
                        limits:
                          cpu: 100m
                          memory: 64Mi
          typhaDeployment:
            spec:
              template:
                spec:
                  initContainers:
                    - name: typha-certs-key-cert-provisioner
                      resources:
                        requests:
                          cpu: 50m
                          memory: 32Mi
                        limits:
                          cpu: 100m
                          memory: 64Mi
                  containers:
                    - name: calico-typha
                      resources:
                        requests:
                          cpu: 50m
                          memory: 64Mi
                        limits:
                          cpu: 100m
                          memory: 128Mi
          calicoNetwork:
            bgp: Disabled
            ipPools:
              - allowedUses:
                  - Workload
                  - Tunnel
                assignmentMode: Automatic
                blockSize: 26
                cidr: {{ .Values.config.podSubnet }}
                disableBGPExport: false
                disableNewAllocations: false
                encapsulation: VXLAN
                name: default-ipv4-ippool
                natOutgoing: Enabled
                nodeSelector: all()
  destination:
    name: {{ .Release.Namespace }}/{{ $name }}
    namespace: tigera-operator
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: -1
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 60s
