# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/argoproj.io/application_v1alpha1.json
{{ $name := include "cluster.fullname" . -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Namespace }}-{{ $name }}-system-cert-manager
  namespace: {{ .Values.argocdNamespace }}
  labels:
    {{- include "cluster.labels" . | nindent 4 }}
spec:
  project: {{ .Release.Namespace }}-{{ $name }}-system
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: {{ .Values.versions.certManager }}
    helm:
      releaseName: cert-manager
      valuesObject:
        extraArgs:
          - --dns01-recursive-nameservers=1.1.1.1:53
        crds:
          enabled: true
        config:
          apiVersion: controller.config.cert-manager.io/v1alpha1
          kind: ControllerConfiguration
          enableGatewayAPI: true
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 50m
            memory: 64Mi
        webhook:
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 50m
              memory: 64Mi
        cainjector:
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 50m
              memory: 128Mi
  destination:
    name: {{ .Release.Namespace }}/{{ $name }}
    namespace: cert-manager
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: -1
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 60s
