{{ $name := include "cluster.fullname" . -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Namespace }}-{{ $name }}-components
  namespace: {{ .Values.argocdNamespace }}
  labels:
    {{- include "cluster.labels" . | nindent 4 }}
spec:
  project: {{ .Release.Namespace }}-{{ $name }}-system
  source:
    chart: cluster-components
    repoURL: ghcr.io/sneakybugs
    targetRevision: {{ .Values.versions.components }}
    helm:
      releaseName: cluster-components
      valuesObject:
        externalSecrets: {{- toYaml .Values.config.externalSecrets | nindent 10 }}
        externalDNSWebhook: {{- toYaml .Values.config.externalDNSWebhook | nindent 10 }}
        certManager: {{- toYaml .Values.config.certManager | nindent 10 }}
        velero:
          externalSecret: {{- toYaml .Values.config.velero.externalSecret | nindent 12 }}
        openTelemetry:
          exporterOTLPEndpoint: {{ .Values.config.otlpExporter.endpoint }}
  destination:
    name: {{ .Release.Namespace }}/{{ $name }}
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
