# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/argoproj.io/application_v1alpha1.json
{{ $name := include "cluster.fullname" . -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Namespace }}-{{ $name }}-system-external-secrets
  namespace: {{ .Values.argocdNamespace }}
  labels:
    {{- include "cluster.labels" . | nindent 4 }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Release.Namespace }}-{{ $name }}-system
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: {{ .Values.versions.externalSecrets }}
    helm:
      releaseName: external-secrets
      valuesObject:
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 150m
            memory: 256Mi
  destination:
    name: {{ .Release.Namespace }}/{{ $name }}
    namespace: external-secrets
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: -1
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 60s
