{{ $name := include "cluster.fullname" . -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ printf "%s-%s-fluent-operator" .Release.Namespace $name }}
  namespace: {{ .Values.argocdNamespace }}
  labels:
    {{- include "cluster.labels" . | nindent 4 }}
spec:
  project: {{ printf "%s-%s-system" .Release.Namespace $name }}
  source:
    repoURL: https://github.com/fluent/fluent-operator.git
    path: charts/fluent-operator
    targetRevision: {{ .Values.versions.fluentOperator }}
    helm:
      releaseName: fluent-operator
      valuesObject:
        containerRuntime: crio
        # Disable the default FluentBit pipeline because it does not fit our stack.
        kubernetes: false

  destination:
    name: {{ .Release.Namespace }}/{{ $name }}
    namespace: telemetry
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
