# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/argoproj.io/application_v1alpha1.json
{{ if .Values.features.kro -}}
{{ $name := include "cluster.fullname" . -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Namespace }}-{{ $name }}-kro
  namespace: {{ .Values.argocdNamespace }}
  labels:
    {{- include "cluster.labels" . | nindent 4 }}
spec:
  project: {{ .Release.Namespace }}-{{ $name }}-system
  source:
    chart: kro
    repoURL: ghcr.io/kro-run/kro
    targetRevision: {{ .Values.versions.kro }}
    helm:
      releaseName: kro
  destination:
    name: {{ .Release.Namespace }}/{{ $name }}
    namespace: kro
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: -1
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 60s
{{- end }}
