# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/argoproj.io/application_v1alpha1.json
{{ $name := include "cluster.fullname" . -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Namespace }}-{{ $name }}-system-openebs
  namespace: {{ .Values.argocdNamespace }}
  labels:
    {{- include "cluster.labels" . | nindent 4 }}
spec:
  project: {{ .Release.Namespace }}-{{ $name }}-system
  source:
    chart: openebs
    repoURL: https://openebs.github.io/openebs
    targetRevision: {{ .Values.versions.openEBS }}
    helm:
      releaseName: openebs
      valuesObject:
        engines:
          replicated:
            mayastor:
              enabled: false
          local:
            zfs:
              enabled: false
            lvm:
              enabled: false
        loki:
          enabled: false
        alloy:
          enabled: false
        localpv-provisioner:
          localpv:
            image:
              registry: docker.io
          hostpathClass:
            isDefaultClass: true
  destination:
    name: {{ .Release.Namespace }}/{{ $name }}
    namespace: openebs
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: -1
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 60s
