# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/argoproj.io/application_v1alpha1.json
{{ if .Values.features.telemetryExporter -}}
{{ $name := include "cluster.fullname" . -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ printf "%s-%s-otel-operator" .Release.Namespace $name }}
  namespace: {{ .Values.argocdNamespace }}
  labels:
    {{- include "cluster.labels" . | nindent 4 }}
spec:
  project: {{ printf "%s-%s-system" .Release.Namespace $name }}
  source:
    chart: opentelemetry-operator
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    targetRevision: {{ .Values.versions.openTelemetryOperator }}
    helm:
      releaseName: opentelemetry-operator
      valuesObject:
        manager:
          collectorImage:
            repository: "otel/opentelemetry-collector-contrib"
  destination:
    name: {{ .Release.Namespace }}/{{ $name }}
    namespace: telemetry
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: -1
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 60s
{{- end }}
