{{ $name := include "cluster.fullname" . -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ printf "%s-%s-node-exporter" .Release.Namespace $name }}
  namespace: {{ .Values.argocdNamespace }}
  labels:
    {{- include "cluster.labels" . | nindent 4 }}
spec:
  project: {{ printf "%s-%s-system" .Release.Namespace $name }}
  source:
    chart: prometheus-node-exporter
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: {{ .Values.versions.prometheusNodeExporter }}
    helm:
      releaseName: prometheus-node-exporter
      valuesObject:
        prometheus:
          monitor:
            enabled: true
  destination:
    name: {{ .Release.Namespace }}/{{ $name }}
    namespace: telemetry
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
