# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/argoproj.io/application_v1alpha1.json
{{ if .Values.features.telemetryExporter -}}
{{ $name := include "cluster.fullname" . -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ printf "%s-%s-prometheus-crds" .Release.Namespace $name }}
  namespace: {{ .Values.argocdNamespace }}
  labels:
    {{- include "cluster.labels" . | nindent 4 }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ printf "%s-%s-system" .Release.Namespace $name }}
  source:
    chart: prometheus-operator-crds
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: {{ .Values.versions.prometheusOperatorCRDs }}
    helm:
      releaseName: prometheus-operator-crds
  destination:
    name: {{ .Release.Namespace }}/{{ $name }}
    namespace: kube-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ServerSideApply=true
      - ServerSideApply=true
    retry:
      limit: -1
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 60s
{{- end }}
