# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/argoproj.io/application_v1alpha1.json
{{ $name := include "cluster.fullname" . -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Namespace }}-{{ $name }}-rook
  namespace: {{ .Values.argocdNamespace }}
  labels:
    {{- include "cluster.labels" . | nindent 4 }}
spec:
  project: {{ .Release.Namespace }}-{{ $name }}-system
  source:
    chart: rook-ceph
    repoURL: https://charts.rook.io/release
    targetRevision: {{ .Values.versions.rook }}
    helm:
      releaseName: rook-ceph
      valuesObject:
        obcAllowAdditionalConfigFields: maxObjects,maxSize,bucketPolicy,bucketLifecycle,bucketOwner
  destination:
    name: {{ .Release.Namespace }}/{{ $name }}
    namespace: rook-ceph
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: -1
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 60s
