{{ $name := include "cluster.fullname" . -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ printf "%s-%s-telemetry-exporter-components" .Release.Namespace $name }}
  namespace: {{ .Values.argocdNamespace }}
  labels:
    {{- include "cluster.labels" . | nindent 4 }}
spec:
  project: {{ printf "%s-%s-system" .Release.Namespace $name }}
  source:
    chart: telemetry-exporter-components
    repoURL: ghcr.io/sneakybugs
    targetRevision: {{ .Values.versions.telemetryExporterComponents }}
    helm:
      releaseName: telemetry-exporter-components
      valuesObject:
        exporterOTLPEndpoint: {{ .Values.config.otlpExporter.endpoint }}
        clusterName: {{ .Release.Namespace }}/{{ $name }}
  destination:
    name: {{ .Release.Namespace }}/{{ $name }}
    namespace: telemetry
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
