# Default values for telemetry-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

argocdNamespace: argocd
destinationCluster: cluster
openTelemetryOperator:
  chartVersion: 0.62.0
fluentOperator:
  chartVersion: v2.9.0
prometheusOperatorCRDs:
  chartVersion: 12.0.0
kubeStateMetrics:
  chartVersion: 5.20.0
prometheusNodeExporter:
  chartVersion: 4.36.0
