# Default values for cluster-components.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: "" # Override chart name.
fullnameOverride: "" # Override full release name.

gateway:
  gatewayClassName: envoy # GatewayClass name to use for the Gateway.
  name: external # Name of the Gateway.
  namespace: envoy # Namespace of the Gateway.
  listeners: # List of listeners for the gateway. Must specify hostname, can optionally specify protocol, port and tls.
    - hostname: "*.example.com"
      # protocol: TLS
      # port: 6443
      # tls:
      #   mode: Passthrough

externalSecrets:
  clusterSecretStoreName: management # Name of configured ClusterSecretStore.
  remoteNamespace: tenant-secrets # Namespace in the remote cluster to fetch secrets from.
  url: https://0.0.0.0:6443 # URL of the remote cluster Kubernetes API.
  serviceAccountTokenSecret:
    name: management-serviceaccount-token # Name of ServiceAccount token secret.
    namespace: kube-system # Namespace of ServiceAccount token secret.

externalDNSWebhook:
  namespace: external-dns # Namespace to create and deploy ExternalDNS configurations in.
  apiEndpoint: http://example.com/v1 # DNS API server endpoint.
  zones: # List of zones managed by ExternalDNS
    - example.com.
  externalSecret:
    remoteKey: external-dns # Secret name in externalSecrets.remoteNamespace namespace in the management cluster.
    idProperty: id # Key of DNS API service account ID in the remote secret.
    secretProperty: secret # Key of DNS API service account secret in the remote secret.

certManager:
  namespace: cert-manager # Namespace to deploy Cert Manager resources in.
  stagingEnvironment: false # Use Let's Encrypt staging server when true.
  clusterIssuerName: letsencrypt # Name of the created ClusterIssuer.
  externalSecret:
    remoteKey: cert-manager # Secret name in externalSecrets.remoteNamespace namespace in the management cluster.
    cloudflareTokenProperty: cloudflareToken # Key of Cloudflare token in the remote secret.

velero:
  enabled: true # Create Velero backup related resources when true.
  rookNamespace: rook-ceph # Rook namespace to use for backup ObjectBucketClaim in the management cluster.
  credentialsSecretRemoteKey: example # Rook CephObjectStoreUser secret name in the management cluster.
  namespace: velero # Namespace to deploy Velero resources in.

cephCSIRBD:
  namespace: ceph-csi-rbd # Namespace where Ceph CSI RBD plugin is installed in the tenant cluster.
  rookNamespace: rook-ceph # Rook namespace in the management cluster for Ceph clients and Rados namespace.
  provisionerClientSecretRemoteKey: example # Name of the Ceph client secret for the CSI provisioner client.
  nodeClientSecretRemoteKey: example # Name of the ceph client secret for the CSI node client.
  cephClusterID: external # Cluster ID to use for the StorageClass. Must be configured in the Ceph CSI RBD chart.
  cephPool: ceph-blockpool # RBD pool to use for the StorageClass.
