# Default values for cluster-components.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: "" # Override chart name.
fullnameOverride: "" # Override full release name.

externalSecrets:
  clusterSecretStoreName: management # Name of configured ClusterSecretStore.
  remoteNamespace: tenant-secrets # Namespace in the remote cluster to fetch secrets from.
  url: https://10.1.0.10:6443 # URL of the remote cluster Kubernetes API.
  serviceAccountTokenSecret:
    name: management-serviceaccount-token # Name of ServiceAccount token secret.
    namespace: kube-system # Namespace of ServiceAccount token secret.

externalDNSWebhook:
  namespace: external-dns # Namespace to create and deploy ExternalDNS configurations in.
  apiEndpoint: http://dns.infra.sneakybugs.com/v1 # DNS API server endpoint.
  zones: # List of zones managed by ExternalDNS
    - example.com.
  externalSecret:
    remoteKey: external-dns # Secret name in externalSecrets.remoteNamespace namespace in the management cluster.
    idProperty: id # Key of DNS API service account ID in the remote secret.
    secretProperty: secret # Key of DNS API service account secret in the remote secret.

certManager:
  namespace: cert-manager # Namespace to deploy Cert Manager resources in.
  stagingEnvironment: false # Use Let's Encrypt staging server when true.
  clusterIssuerName: letsencrypt # Name of the created ClusterIssuer.
  cloudflareEmail: redacted # Cloudflare email for ACME DNS challenge.
  cloudflareZones: # List of DNS zones for ACME DNS challenge (without trailing dot).
    - example.com
  externalSecret:
    remoteKey: cert-manager # Secret name in externalSecrets.remoteNamespace namespace in the management cluster.
    cloudflareTokenProperty: cloudflareToken # Key of Cloudflare token in the remote secret.

velero:
  namespace: velero # Namespace to deploy Velero resources in.
  externalSecret:
    remoteKey: backup # Secret name in externalSecrets.remoteNamespace namespace in the management cluster.
    veleroCredentialsProperty: veleroCredentials # Key of the Velero credentials config.

openTelemetry:
  namespace: telemetry # Namespace to deploy OpenTelemetry resources in.
  exporterOTLPEndpoint: otel.infra.sneakybugs.com:4317 # Centralized OpenTelemetry Collector endpoint to export telemetry to.
