apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: {{ include "cluster.fullname" . }}
  labels:
    {{- include "cluster.labels" . | nindent 4 }}
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs: {}
      files:
        - path: /etc/containers/registries.conf
          content: |
            {{- range .Values.config.imageRegistries }}
            [[registry]]
            prefix = {{ quote .prefix }}
            location = {{ quote .location }}
            {{- end }}
