# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/controlplane.cluster.x-k8s.io/kubeadmcontrolplane_v1beta1.json
{{ $name := include "cluster.fullname" . -}}
kind: KubeadmControlPlane
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
metadata:
  name: {{ include "cluster.fullname" . }}
  labels:
    {{- include "cluster.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.nodes.controlPlane.replicas }}
  machineTemplate:
    infrastructureRef:
      kind: KubevirtMachineTemplate
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
      name: {{ $name }}-control-plane
      namespace: {{ .Release.Namespace }}
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        extraArgs:
          tracing-config-file: /etc/kubernetes/apiserver/tracing-configuration.yaml
        extraVolumes:
          - hostPath: /etc/kubernetes/apiserver
            mountPath: /etc/kubernetes/apiserver
            name: configs
      controllerManager:
        extraArgs:
          bind-address: 0.0.0.0
      scheduler:
        extraArgs:
          bind-address: 0.0.0.0
      etcd:
        local:
          extraArgs:
            listen-metrics-urls: http://0.0.0.0:2381
            experimental-enable-distributed-tracing: "true"
            experimental-distributed-tracing-address: telemetry-system-components-collector.telemetry-system.svc.cluster.local:4317
      networking:
        dnsDomain: cluster.local
        podSubnet: {{ .Values.config.podSubnet }}
        serviceSubnet: {{ .Values.config.serviceSubnet }}
    files:
      - path: /etc/kubernetes/apiserver/tracing-configuration.yaml
        owner: "root:root"
        permissions: "0644"
        content: |
          apiVersion: apiserver.config.k8s.io/v1beta1
          kind: TracingConfiguration
          endpoint: telemetry-system-components-collector.telemetry-system.svc.cluster.local:4317
          samplingRatePerMillion: 10000
      - path: /etc/kubernetes/kubelet/config.yaml
        owner: "root:root"
        permissions: "0644"
        content: |
          apiVersion: kubelet.config.k8s.io/v1beta1
          kind: KubeletConfiguration
          authentication:
            webhook:
              enabled: true
          authorization:
            mode: Webhook
      - path: /etc/containers/registries.conf
        content: |
          unqualified-search-registries = ["docker.io"]
          {{- range .Values.config.imageRegistries }}
          [[registry]]
          prefix = {{ quote .prefix }}
          location = {{ quote .location }}
          {{- end }}
  version: {{ .Values.config.version | quote }}
