{{ $name := include "cluster.fullname" . -}}
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: {{ $name }}-md-0
  labels:
    {{- include "cluster.labels" . | nindent 4 }}
spec:
  clusterName: {{ $name }}
  replicas: {{ .Values.config.workers.replicas }}
  template:
    spec:
      clusterName: {{ $name }}
      version: {{ .Values.config.version | quote }}
      bootstrap:
        configRef:
          name: {{ $name }}
          namespace: {{ .Release.Namespace }}
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
      infrastructureRef:
        name: {{ $name }}-{{ .Values.config.workers.machineTemplate }}
        namespace: {{ .Release.Namespace }}
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
        kind: KubevirtMachineTemplate
