apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KubevirtMachineTemplate
metadata:
  {{- $cpConfig := printf "%s:%s" .Values.config.image (toJson (omit .Values.config.controlPlane "replicas")) }}
  {{- $cpID := sha256sum $cpConfig | trunc 8 }}
  name: {{ include "cluster.fullname" . }}-cp-{{ $cpID }}
  labels:
    {{- include "cluster.labels" . | nindent 4 }}
  annotations:
    {{/* CAPI needs old MachineTemplates during cluster upgrades and deletion, and deletes them when done. */}}
    helm.sh/resource-policy: keep
spec:
  template:
    spec:
      virtualMachineBootstrapCheck:
        checkStrategy: ssh
      virtualMachineTemplate:
        metadata:
          namespace: {{ .Release.Namespace }}
        spec:
          dataVolumeTemplates:
            - apiVersion: cdi.kubevirt.io/v1beta1
              kind: DataVolume
              metadata:
                name: disk
              spec:
                source:
                  http:
                    url: {{ .Values.config.image }}
                pvc:
                  accessModes:
                    - ReadWriteOnce
                  resources:
                    requests:
                      storage: {{ .Values.config.controlPlane.resources.storage }}
          runStrategy: Always
          template:
            spec:
              domain:
                cpu:
                  cores: {{ .Values.config.controlPlane.resources.cores }}
                memory:
                  guest: {{ .Values.config.controlPlane.resources.memory }}
                devices:
                  networkInterfaceMultiqueue: true
                  watchdog:
                    name: watchdog0
                    i6300esb:
                      action: poweroff
                  disks:
                    - disk:
                        bus: virtio
                      name: disk
                  interfaces:
                    - name: cluster
                      bridge: {}
              evictionStrategy: External
              volumes:
                - name: disk
                  dataVolume:
                    name: disk
              networks:
                - name: cluster
                  pod: {}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KubevirtMachineTemplate
metadata:
  {{- $wConfig := printf "%s:%s" .Values.config.image (toJson (omit .Values.config.workers "replicas")) }}
  {{- $wID := sha256sum $wConfig | trunc 8 }}
  name: {{ include "cluster.fullname" . }}-workers-{{ $wID }}
  labels:
    {{- include "cluster.labels" . | nindent 4 }}
  annotations:
    {{/* CAPI needs old MachineTemplates during cluster upgrades and deletion, and deletes them when done. */}}
    helm.sh/resource-policy: keep
spec:
  template:
    spec:
      virtualMachineBootstrapCheck:
        checkStrategy: ssh
      virtualMachineTemplate:
        metadata:
          namespace: {{ .Release.Namespace }}
        spec:
          dataVolumeTemplates:
            - apiVersion: cdi.kubevirt.io/v1beta1
              kind: DataVolume
              metadata:
                name: disk
              spec:
                source:
                  http:
                    url: {{ .Values.config.image }}
                pvc:
                  accessModes:
                    - ReadWriteOnce
                  resources:
                    requests:
                      storage: {{ .Values.config.workers.resources.storage }}
          runStrategy: Always
          template:
            spec:
              domain:
                cpu:
                  cores: {{ .Values.config.workers.resources.cores }}
                memory:
                  guest: {{ .Values.config.workers.resources.memory }}
                devices:
                  networkInterfaceMultiqueue: true
                  watchdog:
                    name: watchdog0
                    i6300esb:
                      action: poweroff
                  disks:
                    - disk:
                        bus: virtio
                      name: disk
                  interfaces:
                    - name: cluster
                      bridge: {}
              evictionStrategy: External
              volumes:
                - name: disk
                  dataVolume:
                    name: disk
              networks:
                - name: cluster
                  pod: {}
