{{ range .Values.machineTemplates }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KubevirtMachineTemplate
metadata:
  name: {{ include "cluster.fullname" $ }}-{{ .name }}
  labels:
    {{- include "cluster.labels" $ | nindent 4 }}
spec:
  template:
    spec:
      virtualMachineBootstrapCheck:
        checkStrategy: ssh
      virtualMachineTemplate:
        metadata:
          namespace: {{ $.Release.Namespace }}
        spec:
          dataVolumeTemplates:
            - apiVersion: cdi.kubevirt.io/v1beta1
              kind: DataVolume
              metadata:
                name: disk
              spec:
                source:
                  http:
                    url: {{ .image }}
                pvc:
                  accessModes:
                    - ReadWriteOnce
                  resources:
                    requests:
                      storage: {{ .resources.storage }}
          runStrategy: Always
          template:
            spec:
              domain:
                cpu:
                  cores: {{ .resources.cores }}
                memory:
                  guest: {{ .resources.memory }}
                devices:
                  networkInterfaceMultiqueue: true
                  watchdog:
                    name: watchdog0
                    i6300esb:
                      action: poweroff
                  disks:
                    - disk:
                        bus: virtio
                      name: disk
                  interfaces:
                    - name: cluster
                      bridge: {}
              evictionStrategy: External
              volumes:
                - name: disk
                  dataVolume:
                    name: disk
              networks:
                - name: cluster
                  pod: {}
{{- end }}
