# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/objectbucket.io/objectbucketclaim_v1alpha1.json
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
{{ $bucketName := printf "%s-%s-backup" .Release.Namespace (include "postgres.fullname" .) -}}
{{ $userName := $bucketName -}}
metadata:
  name: {{ $bucketName }}
  # namespace: {{ .Values.backups.rookNamespace }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  bucketName: {{ $bucketName }}
  storageClassName: {{ .Values.backups.cephObjectBucketStorageClassName }}
  additionalConfig:
    bucketPolicy: |
      {
          "Version": "2012-10-17",
          "Statement": [
              {
                  "Effect": "Allow",
                  "Principal": {
                      "AWS": "arn:aws:iam:::user/{{ $userName }}"
                  },
                  "Action": "s3:ListBucket",
                  "Resource": [
                      "arn:aws:s3:::{{ $bucketName }}"
                  ]
              },
              {
                  "Effect": "Allow",
                  "Principal": {
                      "AWS": "arn:aws:iam:::user/{{ $userName }}"
                  },
                  "Action": ["s3:GetObject", "s3:DeleteObject", "s3:PutObject", "s3:PutObjectTagging", "s3:AbortMultipartUpload", "s3:ListMultipartUploadParts"],
                  "Resource": [
                      "arn:aws:s3:::{{ $bucketName }}/*"
                  ]
              }
          ]
      }
---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/ceph.rook.io/cephobjectstoreuser_v1.json
apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
  name: {{ $userName }}
  # namespace: {{ .Values.backups.rookNamespace }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  store: {{ .Values.backups.cephObjectStoreName }}
  displayName: {{ $bucketName }} backup
---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/barmancloud.cnpg.io/objectstore_v1.json
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  retentionPolicy: {{ .Values.backups.retentionPolicy }}
  configuration:
    destinationPath: s3://{{ $bucketName }}/
    endpointURL: {{ .Values.backups.s3Endpoint }}
    s3Credentials:
      accessKeyId:
        name: {{ $userName }}
        key: AWS_ACCESS_KEY_ID
      secretAccessKey:
        name: {{ $userName }}
        key: AWS_SECRET_ACCESS_KEY
    data:
      compression: bzip2
    wal:
      compression: bzip2
