{{ $name := include "cluster.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}-token
  labels:
    {{- include "cluster.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ $name }}
type: kubernetes.io/service-account-token
