{{ $name := include "cluster.fullname" . -}}
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ $name }}-serviceaccount
  labels:
    {{- include "cluster.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: {{ $name }}
      kind: SecretStore
  selector:
    secret:
      name: {{ $name }}-token
  template:
    metadata:
      annotations: {}
      labels: {}
  data:
    - match:
        secretKey: ca.crt
        remoteRef:
          remoteKey: management-serviceaccount-token
          property: ca.crt
    - match:
        secretKey: namespace
        remoteRef:
          remoteKey: management-serviceaccount-token
          property: namespace
    - match:
        secretKey: token
        remoteRef:
          remoteKey: management-serviceaccount-token
          property: token
