nameOverride: "" # Override chart name.
fullnameOverride: "" # Override full release name.
argocdNamespace: argocd # Namespace to deploy Argo CD resources to.

versions:
  calico: v3.28.0 # Calico version to deploy.
  certManager: v1.15.0 # Cert Manager version to deploy.
  components: 1.0.0 # cluster-components chart version to deploy.
  externalDNS: 1.14.5 # ExternalDNS version to deploy.
  openEBS: 4.0.1 # OpenEBS version to deploy.
  traefik: 28.1.0 # Traefik version to deploy.

config:
  podSubnet: 10.243.0.0/16 # Pod subnet to use.
  serviceSubnet: 10.95.0.0/16 # Service subnet to use.
  image: http://10.1.0.13:8000/rocky-9.qcow2 # Node image to use.
  version: 1.31.0 # Kubernetes version of the node image.

  traefik:
    ingressHostname: ingress.services.infra.sneakybugs.com # Hostname to set for the ingress service with ExternalDNS.

  externalDNSWebhook: {} # Values for cluster-components chart externalDNSWebhook field.
    # serviceAccountID: example
    # serviceAccountSecret: example
    # zones:
    #   - example.com.

  certManager: {} # Values for cluster-components chart certManager field.
    # cloudflareToken: redacted
    # cloudflareEmail: redacted
    # cloudflareZones:
    #   - example.com

nodes:
  controlPlane:
    replicas: 1 # Control plane node count.
    resources:
      storage: 16Gi # Control plane node disk size.
      cores: 2 # Control plane node core count.
      memory: 4Gi # Control plane node RAM size.

  worker:
    replicas: 1 # Worker node count.
    resources:
      storage: 32Gi # Worker node disk size.
      cores: 4 # Worker node core count.
      memory: 8Gi # Worker node RAM size.
