{{ $name := include "cluster.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}-ccm
  labels:
    capk.cluster.x-k8s.io/template-kind: extra-resource
    cluster.x-k8s.io/cluster-name: {{ $name }}
data:
  cloud-config: |
    loadBalancer:
      creationPollInterval: 5
      creationPollTimeout: 60
    namespace: {{ .Release.Namespace }}
    instancesV2:
      enabled: true
      zoneAndRegionEnabled: false
