{{ $name := include "cluster.fullname" . -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    capk.cluster.x-k8s.io/template-kind: extra-resource
    cluster.x-k8s.io/cluster-name: {{ $name }}
  name: {{ $name}}-ccm
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $name}}-ccm
subjects:
- kind: ServiceAccount
  name: {{ $name}}-ccm
  namespace: {{ .Release.Namespace }}
