{{ $name := include "cluster.fullname" . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    capk.cluster.x-k8s.io/template-kind: extra-resource
    cluster.x-k8s.io/cluster-name: {{ $name }}
  name: {{ $name }}-ccm
