{{ $name := include "cluster.fullname" . -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Namespace }}-{{ $name }}-components
  namespace: {{ .Values.argocdNamespace }}
spec:
  project: {{ .Release.Namespace }}-{{ $name }}-system
  source:
    chart: cluster-components
    repoURL: ghcr.io/sneakybugs
    targetRevision: {{ .Values.versions.components }}
    helm:
      releaseName: cluster-components
      valuesObject:
        externalDNSWebhook: {{- toYaml .Values.config.externalDNSWebhook | nindent 10 }}
        certManager: {{- toYaml .Values.config.certManager | nindent 10 }}
  destination:
    name: {{ .Release.Namespace }}/{{ $name }}
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
