apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KubevirtCluster
metadata:
  name: {{ include "cluster.fullname" . }}
spec:
  controlPlaneServiceTemplate:
    spec:
      type: LoadBalancer
