{{ $name := include "cluster.fullname" . -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Namespace }}-{{ $name }}
  namespace: {{ .Values.config.rbac.namespace }}
rules: {{- toYaml .Values.config.rbac.rules | nindent 2 }}
