# Default values for telemetry-system.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: "" # Override chart name.
fullnameOverride: "" # Override full release name.

argocdNamespace: argocd # Namespace to deploy Argo CD resources to.
destinationCluster: cluster # Name of the destination cluster, must be in the same namespace as this chart is deployed in.
destinationClusterDomain: cluster.local # Domain used for networking.dnsDomain in Kubeadm for the tenant cluster.

kubePrometheusStack:
  chartVersion: 62.1.0 # Kube Prometheus Stack chart version to deploy.
  grafana:
    adminUser: admin # Default Grafana admin username.
    adminPassword: admin # Default Grafana admin password.
    host: grafana.infra.sneakybugs.com # Grafana hostname to set using ExternalDNS.

tempo:
  chartVersion: 1.9.0 # Grafana Tempo chart version to deploy.

loki:
  chartVersion: 6.10.0 # Grafana Loki chart version to deploy.
