# Default values for telemetry-system.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: "" # Override chart name.
fullnameOverride: "" # Override full release name.

argocdNamespace: argocd # Namespace to deploy Argo CD resources to.
destinationCluster: cluster # Name of the destination cluster, must be in the same namespace as this chart is deployed in.

versions:
  grafanaOperator: v5.19.4
  kubePrometheusStack: 77.11.0
  clickhouseOperator: 0.25.4

config: {}
