# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/ceph.rook.io/cephblockpoolradosnamespace_v1.json
{{- if not .Values.config.cephCSIRBD.existingRadosNamespace }}
apiVersion: ceph.rook.io/v1
kind: CephBlockPoolRadosNamespace
metadata:
  name: {{ .Release.Namespace }}-{{ include "cluster.fullname" . }}
  namespace: {{ .Values.config.cephCSIRBD.rookNamespace }}
  labels:
    {{- include "cluster.labels" . | nindent 4 }}
  annotations:
    rook.io/force-deletion: "true"
    {{- if .Values.features.backups }}
    helm.sh/resource-policy: keep
    {{- end }}
spec:
  blockPoolName: {{ .Values.config.cephCSIRBD.blockPoolName }}
{{- end }}
