apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cluster-components.fullname" . }}-cert-manager-token
  namespace: {{ .Values.certManager.namespace }}
  labels:
    {{- include "cluster-components.labels" . | nindent 4 }}
stringData:
  cloudflareToken: {{ .Values.certManager.cloudflareToken }}
