# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/clustersecretstore_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.externalSecrets.clusterSecretStoreName }}
  labels:
    {{- include "cluster-components.labels" . | nindent 4 }}
spec:
  provider:
    kubernetes:
      remoteNamespace: {{ .Values.externalSecrets.remoteNamespace }}
      server:
        url: {{ .Values.externalSecrets.url }}
        caProvider:
          type: Secret
          name: {{ .Values.externalSecrets.serviceAccountTokenSecret.name }}
          namespace: {{ .Values.externalSecrets.serviceAccountTokenSecret.namespace }}
          key: ca.crt
      auth:
        token:
          bearerToken:
            name: {{ .Values.externalSecrets.serviceAccountTokenSecret.name }}
            namespace: {{ .Values.externalSecrets.serviceAccountTokenSecret.namespace }}
            key: token
