apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cluster-components.fullname" . }}-external-dns-webhook
  namespace: {{ .Values.externalDNSWebhook.namespace }}
  labels:
    {{- include "cluster-components.labels" . | nindent 4 }}
data:
  apiEndpoint: {{ .Values.externalDNSWebhook.apiEndpoint }}
  zones: {{ .Values.externalDNSWebhook.zones }}
