# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
{{ $name := include "cluster-components.fullname" . -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $name }}-external-dns-webhook
  namespace: {{ .Values.externalDNSWebhook.namespace }}
  labels:
    {{- include "cluster-components.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecrets.clusterSecretStoreName }}
  target:
    name: {{ $name }}-external-dns-webhook
  data:
  - secretKey: id
    remoteRef:
      key: {{ .Values.externalDNSWebhook.externalSecret.remoteKey }}
      property: {{ .Values.externalDNSWebhook.externalSecret.idProperty }}
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
  - secretKey: secret
    remoteRef:
      key: {{ .Values.externalDNSWebhook.externalSecret.remoteKey }}
      property: {{ .Values.externalDNSWebhook.externalSecret.secretProperty }}
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
