apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cluster-components.fullname" . }}-external-dns-webhook
  namespace: {{ .Values.externalDNSWebhook.namespace }}
  labels:
    {{- include "cluster-components.labels" . | nindent 4 }}
stringData:
  id: {{ .Values.externalDNSWebhook.serviceAccountID }}
  secret: {{ .Values.externalDNSWebhook.serviceAccountSecret }}
