apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cluster-components.fullname" . }}-targetallocator
  namespace: {{ .Values.openTelemetry.namespace }}
  labels:
    {{- include "cluster-components.labels" . | nindent 4 }}
