# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
{{ if .Values.velero.enabled -}}
{{ $name := include "cluster-components.fullname" . -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $name }}-velero-serviceaccount
  namespace: {{ .Values.velero.namespace }}
  labels:
    {{- include "cluster-components.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecrets.clusterSecretStoreName }}
  target:
    name: {{ $name }}-backup
  data:
  - secretKey: veleroCredentials
    remoteRef:
      key: {{ .Values.velero.externalSecret.remoteKey }}
      property: {{ .Values.velero.externalSecret.veleroCredentialsProperty }}
{{- end }}
