# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
{{ if .Values.velero.enabled -}}
{{ $name := include "cluster-components.fullname" . -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ceph-object-user-velero
  namespace: {{ .Values.velero.namespace }}
  labels:
    {{- include "cluster-components.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: rook-ceph
  target:
    name: ceph-object-user-velero
    template:
      engineVersion: v2
      data:
        veleroCredentials: |
          [default]
          aws_access_key_id = {{ `{{ .accessKeyID }}` }}
          aws_secret_access_key = {{ `{{ .secretAccessKey }}` }}
  data:
    - secretKey: accessKeyID
      remoteRef:
        key: {{ .Values.velero.credentialsSecretRemoteKey }}
        property: AccessKey
    - secretKey: secretAccessKey
      remoteRef:
        key: {{ .Values.velero.credentialsSecretRemoteKey }}
        property: SecretKey
{{- end }}
