{{ $name := include "telemetry-exporter.fullname" . -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ printf "%s-%s-components" .Release.Namespace $name }}
  namespace: {{ .Values.argocdNamespace }}
  labels:
    {{- include "telemetry-exporter.labels" . | nindent 4 }}
spec:
  project: {{ printf "%s-%s" .Release.Namespace $name }}
  source:
    chart: telemetry-exporter-components
    repoURL: ghcr.io/sneakybugs
    targetRevision: {{ .Values.telemetryExporterComponents.chartVersion }}
    helm:
      releaseName: telemetry-exporter-components
      valuesObject:
        exporterOTLPEndpoint: {{ .Values.config.exporterOTLPEndpoint }}
        clusterName: {{ printf "%s/%s" .Release.Namespace .Values.destinationCluster }}
  destination:
    name: {{ printf "%s/%s" .Release.Namespace .Values.destinationCluster }}
    namespace: telemetry
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
