{{ $name := include "telemetry-exporter.fullname" . -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ printf "%s-%s-kube-state-metrics" .Release.Namespace $name }}
  namespace: {{ .Values.argocdNamespace }}
  labels:
    {{- include "telemetry-exporter.labels" . | nindent 4 }}
spec:
  project: {{ printf "%s-%s" .Release.Namespace $name }}
  source:
    chart: kube-state-metrics
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: {{ .Values.kubeStateMetrics.chartVersion }}
    helm:
      releaseName: kube-state-metrics
      valuesObject:
        prometheus:
          monitor:
            enabled: true
  destination:
    name: {{ printf "%s/%s" .Release.Namespace .Values.destinationCluster }}
    namespace: telemetry
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
